### ISSUE TITLE
Unable to convert heif to jpg taken by iPhone 15 pro

### ISSUE THREAD

**Issue by AudriusAdroiti** [hey-red/ImageSharp.Heif#4]
When trying to convert heif images (taken with iPhone 15 pro) to jpg format, we get an error
`Invalid input: Unspecified: Metadata not correctly assigned to image`

Code snippet which throw an exception
       
```
private static async Task<Stream> EditImageInMemoryAsync(Stream orignalImage, Action<IImageProcessingContext> opereation, IImageFormat format)
        {
            var modifiedImage = new MemoryStream();
            using var image = await Image.LoadAsync(orignalImage);
            image.Mutate(opereation);
            image.Save(modifiedImage, format);
            modifiedImage.Position = 0;
            orignalImage.Position = 0;
            return modifiedImage;
}
```

Similar issue were fixed in this [package](https://github.com/strukturag/libheif/issues/1190).

[bad-images.zip](https://github.com/user-attachments/files/16450807/bad-images.zip) - zip file with images. With these images we get an error.

**Comment by avbelkin** [comment]
Issue looks like fixed in libheif https://github.com/strukturag/libheif/issues/1190#issuecomment-2267169527
Would be happy to see ImageSharp.Heif dependencies update and maintenance release if possible

**Comment by axtox** [comment]
Same error when trying to convert those images to `.webp`. I am using `HeyRed.ImageSharp.Heif` package version `2.1.3` and `libheif` package for docker debian `amd64` version 1.15.1-1+deb12u1

Here's thew full stacktrace and looks like the problem is in the related package that uses libheif API called [LibHeifSharp](https://github.com/0xC0000054/libheif-sharp):
<details><summary>Stack Trace</summary>
<p>

LibHeifSharp.HeifException: Invalid input: Unspecified: Metadata not correctly assigned to image
   at LibHeifSharp.ExceptionUtil.ThrowHeifException(String message)
   at LibHeifSharp.Interop.heif_error.ThrowIfError()
   at LibHeifSharp.HeifContext.HandleFileIOError(IHeifIOError heifIOError, heif_error& error, Boolean wrapIOExceptions)
   at LibHeifSharp.HeifContext.HandleFileReadError(heif_error& error)
   at LibHeifSharp.HeifContext.InitializeContextFromReader()
   at LibHeifSharp.HeifContext..ctor(Stream stream, Boolean leaveOpen)
   at HeyRed.ImageSharp.Heif.HeifDecoderCore.Decode[TPixel](Stream stream, CancellationToken cancellationToken)
   at HeyRed.ImageSharp.Heif.HeifDecoder.Decode[TPixel](HeifDecoderOptions options, Stream stream, CancellationToken cancellationToken)
   at HeyRed.ImageSharp.Heif.HeifDecoder.Decode(HeifDecoderOptions options, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.SpecializedImageDecoder`1.Decode(DecoderOptions options, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoder.<>c__DisplayClass1_0.<Decode>b__0(Stream s)
   at SixLabors.ImageSharp.Formats.ImageDecoder.<WithSeekableStream>g__PerformActionAndResetPosition|11_0[T](Stream s, Int64 position, <>c__DisplayClass11_0`1&)
   at SixLabors.ImageSharp.Formats.ImageDecoder.WithSeekableStream[T](DecoderOptions options, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Formats.ImageDecoder.Decode(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.Decode(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass80_0.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](DecoderOptions options, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load(DecoderOptions options, Stream stream)

</p>
</details> 

Here's my code:
```c#
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.Formats.Bmp;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.Formats.Tiff;
using SixLabors.ImageSharp.Formats.Webp;
using SixLabors.ImageSharp.Processing;
using HeyRed.ImageSharp.Heif.Formats.Avif;
using HeyRed.ImageSharp.Heif.Formats.Heif;

private readonly DecoderOptions decoderOptions = new DecoderOptions
{
    Configuration = new Configuration([
        new WebpConfigurationModule(),
        new JpegConfigurationModule(),
        new JpegConfigurationModule(),
        new PngConfigurationModule(),
        new BmpConfigurationModule(),
        new TiffConfigurationModule(),
        new HeifConfigurationModule(),
        new HeifConfigurationModule(),
        new AvifConfigurationModule(),
    ])
};

public Task<Stream> Process(Stream orioginalImage, CancellationToken cancellation)
{
    orioginalImage.Position = 0;
    using var image = Image.Load(decoderOptions, orioginalImage);
    var outputImage = new MemoryStream();

    // Save the result
    image.Save(outputImage, imageEncoder);
    return Task.FromResult<Stream>(outputImage);
}
```

**Comment by axtox** [comment]
UPD: I've tried to build a latest libheic C++ binaries since there's a version 1.20.1 already available but the [latest available](https://github.com/strukturag/libheif/releases/tag/v1.20.1) custom [build of the libheic from hey-red](https://www.nuget.org/packages/LibHeif.Native) (the author of this repo as well) is the 1.15.1

I've used the script from [main hey-red repo](https://github.com/hey-red/LibHeif-Build/) to build and pack the libraries with no error and faced the problem that the libheic binary does not work, maybe I'm building it wrong, since the cmake files are changed and [this script](https://github.com/hey-red/LibHeif-Build/blob/master/build.sh) does not work, I've made these changes (take a look at the `git -C libheif pull` line of code, the cmake changes are there):

<details><summary>build.sh</summary>
<p>
#!/bin/bash
set -e;

sudo apt install git build-essential autoconf automake cmake libtool rename tar yasm -y

#Set cpu count
cpu_count="$(grep -c processor /proc/cpuinfo 2>/dev/null)"
if [ -z "$cpu_count" ]; then
  echo "Unable to determine cpu count, set default 1"
  cpu_count=1
fi

build_dir=$(pwd)/libheif_build
prefix=$build_dir/dist

export LDFLAGS="-L$prefix/lib -pipe"
export CPPFLAGS="-I$prefix/include -fPIC"
export CFLAGS="-I$prefix/include -mtune=generic -O3 -fPIC -pipe"
export CXXFLAGS="${CFLAGS}"

export PKG_CONFIG_PATH=$prefix/lib/pkgconfig

rm -rf $prefix

mkdir -p $build_dir
mkdir -p $prefix

cd $build_dir
git -C x265_git pull || git clone https://bitbucket.org/multicoreware/x265_git
rm -rf x265_build
mkdir -p x265_build
cd x265_build
cmake -DCMAKE_INSTALL_PREFIX:PATH=$prefix -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 -DENABLE_SHARED=1 -DENABLE_CLI=0 -DENABLE_TESTS=0 ../x265_git/source
make -j$cpu_count && make install
cd ..

git -C aom pull || git clone -b v3.5.0 --depth 1 https://aomedia.googlesource.com/aom 
rm -rf aom_build
mkdir -p aom_build
cd aom_build
cmake -DCMAKE_INSTALL_PREFIX:PATH=$prefix -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=0 -DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 -DENABLE_TESTDATA=0 -DENABLE_TESTS=0 -DENABLE_TOOLS=0 ../aom
make -j$cpu_count && make install
cd ..

git -C libde265 pull || git clone https://github.com/strukturag/libde265.git
cd libde265
./autogen.sh
./configure --prefix=$prefix --disable-shared --enable-static --disable-dec265 --disable-sherlock265
make -j$cpu_count && make install
cd ..

git -C libheif pull || git clone https://github.com/strukturag/libheif
cd libheif
mkdir build
cd build
cmake --preset=release ..
sudo make -j$cpu_count && sudo make install
cd ../..

cd $prefix/lib
#Delete links
find -type l -delete

rm *.*a

mv libx265.so.* libheif.so

tar -czvf libheif-linux-x64.tar.gz *.*
</p>
</details> 

and can't attach the nuget packages that you can use in your local NuGet repo folder to update the version of the LibHeic.Native nuget package, but you can use this repo and build.sh to actually build it for your self, I can descrive the needed changes in the repo to do so

still no luck with this file. how did you get the HEIF format on your iPhone? Friend of my sent me some photos from iPhone 15 Pro and there always HEIC format which works perfectly with this library
